BEGIN TRY

BEGIN TRAN;

-- AddForeignKey
ALTER TABLE [dbo].[Patients] ADD CONSTRAINT [Patients_DepartmentID_fkey] FOREIGN KEY ([DepartmentID]) REFERENCES [dbo].[Departments]([DepartmentID]) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
